# Generated by Django 3.2.8 on 2021-10-11 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeolocationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('type', models.CharField(max_length=4)),
                ('continent_code', models.CharField(blank=True, max_length=2)),
                ('continent_name', models.CharField(blank=True, max_length=20)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('country_name', models.CharField(blank=True, max_length=50)),
                ('region_code', models.CharField(blank=True, max_length=2)),
                ('region_name', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('zip', models.CharField(blank=True, max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=17, max_digits=20, null=True)),
                (
                    'request',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to='geolocations.geolocationrequest'
                    ),
                ),
            ],
        ),
    ]
