# Generated by Django 3.2.8 on 2021-10-11 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='request',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to='geolocation.geolocationrequest'
            ),
        ),
    ]
